### ISSUE TITLE
[doc] Enable wiki

### ISSUE THREAD

**Issue by Freed-Wu** [iterative/shtab#119]
- <https://github.com/google/vimdoc/blob/823e3bbc1944d0377408b602ec10ba0c39a8bf8e/setup.py#L36>
- <https://github.com/andreafrancia/trash-cli/blob/b913bf30b277cecc04f27858d275802684ecac13/setup.cfg#L31-L33>
- <https://github.com/inducer/pudb/blob/1dea19a3a14ba2398e5b7909eb86cad0c0152b3d/setup.py#L24>
- <https://github.com/piccolomo/plotext/blob/f760510cc6957de82c57502c07e4d0c0e4762302/setup.py#L25>
- <https://github.com/wookayin/gpustat/blob/56a9dcf3c99f29065f1215afcff372d01da9f256/setup.py#L116>

**Comment by Freed-Wu** [comment]
@casperdcl

**Comment by Freed-Wu** [comment]
How about enabling a wiki for this project <https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis> and <https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis> and let all people edit it to add new project which use shtab?

**Comment by Freed-Wu** [comment]
@omesser

**Comment by casperdcl** [comment]
unless there's some reason a wiki is better, I'd prefer you open a PR on [the docs](https://github.com/iterative/shtab/tree/main/docs) instead.

**Comment by omesser** [comment]
> unless there's some reason a wiki is better, I'd prefer you open a PR on [the docs](https://github.com/iterative/shtab/tree/main/docs) instead.

not splitting up the content will help keep maintainence overhead lower for us and help focus poeple in one place.
Sounds ok @Freed-Wu?

**Comment by Freed-Wu** [comment]
Oh, I think every package developers who use this project can add their package names to wiki and wiki can be edit directly without creating a PR, which should be easier than opening a PR so it can encourage them to add their package names.

**Comment by casperdcl** [comment]
Perhaps; though I'm sceptical about quality.

FYI things like https://github.com/inducer/pudb/blob/1dea19a3a14ba2398e5b7909eb86cad0c0152b3d/pudb/run.py#L16-L19 and https://github.com/iterative/dvc/blob/2ef2caafd3f7c540caed4cb60fe3d9ff0255caf9/dvc/cli/completion.py are worth mentioning - and such a list would rarely need updating. By comparison, I'm not sure that just linking to `setup.py` files is useful (https://github.com/iterative/shtab/network/dependents is much more up-to-date and impressive).

**Comment by Freed-Wu** [comment]
<https://github.com/iterative/shtab/network/dependents?dependent_type=REPOSITORY> is only for repository, <https://github.com/iterative/shtab/network/dependents?dependent_type=PACKAGE> is the list including all packages depending on shtab and looks good. Can we mention <https://github.com/iterative/shtab/network/dependents?dependent_type=PACKAGE> as a list of example projects which use shtab?
