### ISSUE TITLE
[feature] get completion script from python

### ISSUE THREAD

**Issue by Freed-Wu** [iterative/shtab#126]
If we want get shell completion scripts from python, we must `complete(parser, xxsh, PREAMBLE)`. However,
we can get completion script from shell by `XXX --print-completion xxsh`, don't need PREAMBLE. Why not ignore PREAMBLE, too?

**Comment by casperdcl** [comment]
Preambles can only be defined in the Python API ([`shtab.complete(preamble)`](https://docs.iterative.ai/shtab/ref/#complete) and [`shtab.add_argument_to(preamble)`](https://docs.iterative.ai/shtab/ref/#add_argument_to)].

It seems clunky to support CLI preambles as well.
