### ISSUE TITLE
add a logo

### ISSUE THREAD

**Issue by casperdcl** [iterative/shtab#13]
just made this:

![logo](https://user-images.githubusercontent.com/10780059/88551023-485cf480-d01a-11ea-81b0-6b0383f77d5c.png)

**Comment by shcheklein** [comment]
Looks perfect to me

**Comment by casperdcl** [comment]
do we wanna track it in the repo using dvc, or just commit it directly? It's only 16 kB

**Comment by shcheklein** [comment]
I think Git is fine for this

**Comment by casperdcl** [comment]
![banner](https://user-images.githubusercontent.com/10780059/88596283-ad393e80-d05c-11ea-9b52-3f79c113abd5.png)
