### ISSUE TITLE
setup.py missing?

### ISSUE THREAD

**Issue by aboschke** [iterative/shtab#153]
Shouldn't setup.py still be available in the lastest version? 

404 starts showing up here: [ https://github.com/iterative/shtab/blob/v1.6.2/setup.py ]

**Comment by casperdcl** [comment]
No, this is a new-style[^pep621][^pep517] project using `pyproject.toml`[^pypa][^setuptools][^pep518] instead.

[^pep621]: https://peps.python.org/pep-0621
[^pep517]: https://peps.python.org/pep-0517
[^pep518]: https://peps.python.org/pep-0518
[^pypa]: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata
[^setuptools]: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
