### ISSUE TITLE
Could replace more non-word characters

### ISSUE THREAD

**Issue by dustinlagoy** [iterative/shtab#165]
I have an argparse script which accepts subcommands with names like:

```
my/first/subcommand
my/second/subcommand
```

which end up causing invalid completion scripts similar to #20.

It would be trivial to add `/` to the list of characters replaced in `wordify()`, or even change the character set to `\W` to replace any non-word character. Are either of these options preferable? (both work when tested with my script)

I'm happy to put together a one-line pull request if you think this is worthwhile.

**Comment by casperdcl** [comment]
Sure, please do open a PR :)
