### ISSUE TITLE
Unable to get examples to work from given instructions

### ISSUE THREAD

**Issue by bmorledge-hampton19** [iterative/shtab#24]
I am unable to get the expected functionality out of shtab.  I am hoping to implement tab completion on a personal project of mine, but have not been successful using the instructions in the readme.  While troubleshooting, I thought I would validate that I am doing things correctly by at least activating tab completion on shtab itself.  I have checked that my ~/.bashrc file contains the following entry:

if ! shopt -oq posix; then
 if [ -f /usr/share/bash-completion/bash_completion ]; then
   . /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
 fi
fi

It does.  I then run the following command:

`shtab --shell=bash shtab.main.get_main_parser | sudo tee /usr/share/bash-completion/completions/shtab`

It appears to complete without any issues, and in fact, I can see that the resulting shtab completion file has been added to the given directory.  However, there is no tab complete available for the shtab command.  Am I missing something?

If it helps, I am running Ubuntu 20.04.1 on WSL.

**Comment by casperdcl** [comment]
Have you tried restarting your terminal?

**Comment by bmorledge-hampton19** [comment]
Ah.  Yes that appears to have fixed it.  My bad.  I probably should have tried that to begin with.  Thank you for the assistance!

I have a couple other questions, but I'm not sure if this is the best place to ask them.  I'll state them anyway, but please let me know if there is a better place for me to be posing these questions.

First, I am still having issues getting tab completion to work on my personal project.  I am able to generate the completions file, and I can see in the first couple of lines that it is recognizing the relevant options.  However, tab completion is not available when I access the project through the entry point I have created.  Is it potentially a problem that the entry point command is different from the name of the python package?  (The entry point is named "nucperiod" whereas the python package is named "nucperiodpy")

Second, I am hoping to distribute this package through a ppa so that users can download it with apt.  Is there a way to call the command to generate the completion file during the install process, so that the end user doesn't have to worry about it?  Also, is sourcing ~/.bashrc equivelant to restarting the terminal for the purposes of enabling tab completion?  If not, is there some other way to do this?

Thanks again.  I really appreciate the assistance.

**Comment by casperdcl** [comment]
> The entry point is named "nucperiod" whereas the python package is named "nucperiodpy"

Provided you're using `argparse.ArgumentParser(prog="nucperiod", ...)` then `shtab` will generate completions for `nucperiod`.

> Second, I am hoping to distribute this package through a ppa so that users can download it with apt. Is there a way to call the command to generate the completion file during the install process

You should generate the completions yourself and package them into the distribution, e.g. https://github.com/iterative/dvc/blob/8495b0521bf0001dd1e47b69a93df7e966287e2d/scripts/build_posix.sh#L119-L123 and https://github.com/iterative/dvc/blob/d3931def533f2c1745a1d027d546c98def3576b4/snap/snapcraft.yaml#L48

> is sourcing ~/.bashrc equivelant to restarting the terminal for the purposes of enabling tab completion?

Depends on the versions of `bash` and `bash-completion` as well as the contents of `.bashrc`. It may work but sourcing /usr/share/bash-completion/bash_completion or restarting the terminal is likely safer.

**Comment by bmorledge-hampton19** [comment]
Many, many thanks!  This was very helpful.
