### ISSUE TITLE
subcommand convenience wrapper doesn't work

### ISSUE THREAD

**Issue by casperdcl** [iterative/shtab#25]
https://github.com/iterative/shtab/blob/a01e2b592102496a3a7b6861b448d0d6e78407f4/examples/customcomplete.py#L43 provides completion only for the `subparser` rather than the full (parent) `parser`

**Comment by shcheklein** [comment]
@casperdcl curious, what is the use case here, could you give an example please?

**Comment by casperdcl** [comment]
basically the shtab/examples/customcomplete.py demo doesn't work - the generated completions only complete one subcommand (`customcomplete completion ...`) rather than the root command (`customcomplete ...`).

With #26 (correct convenience function), we can probably halve the number of lines in https://github.com/iterative/dvc/blob/master/dvc/command/completion.py

**Comment by shcheklein** [comment]
so, DVC is not affected at the moment?

**Comment by casperdcl** [comment]
no, not affected because it isn't (yet) using this convenience function.

dvc can benefit from this after merge...

**Comment by shcheklein** [comment]
@casperdcl got it, thanks! 🙏  (that's why it was hard to get the idea, since I was trying it on the DVC and was not seeing any issues).
