### ISSUE TITLE
hide SUPPRESSed options

### ISSUE THREAD

**Issue by skshetry** [iterative/shtab#3]
The suppressed options should not be generated/added to the autocompletion.

**Comment by casperdcl** [comment]
Ah you mean when `help=argparse.SUPPRESS` (`SUPPRESS` is also used for other things).

**Comment by skshetry** [comment]
@casperdcl, yes, the argparse one.

**Comment by casperdcl** [comment]
No I mean argparse also uses `SUPPRESS` for other things other than `help=`.
