### ISSUE TITLE
How to test autocompletion on a local script ?

### ISSUE THREAD

**Issue by Conchylicultor** [iterative/shtab#32]
I'm struggling to make shtab works:

Reproduction instructions:

```sh
# Create a clear environement
bash
mkdir autocomplete
cd autocomplete/

# Add python file
cat <<EOF >>my_script.py
#!/usr/bin/env python
import argparse

def get_main_parser():
    parser = argparse.ArgumentParser(prog="pathcomplete")
    parser.add_argument("--sum", default=None)
    parser.add_argument("--other", default=None)
    return parser


if __name__ == "__main__":
    parser = get_main_parser()
    args = parser.parse_args()
    print(args)
EOF

# Test python file
chmod +x my_script.py
alias my_script=./my_script.py
./my_script.py  --sum=123  # Works
my_script  --sum=123  # Works too

# Try registering autocompletion
shtab --shell=bash my_script.get_main_parser
eval "$(shtab --shell=bash my_script.get_main_parser)"

```
Even after `eval $(shtab ...)` has run successfully, `TAB` does not work either for `my_script` nor `./my_scripts.py`. What am I doing wrong ?

I tested this with `shtab 1.3.5` in both linux and macos

**Comment by casperdcl** [comment]
`prog="pathcomplete"` doesn't match `alias my_script=./my_script.py`

Either:

`prog="my_script"`

Or:

`shtab --prog=my_script ...`

**Comment by Conchylicultor** [comment]
Oh I see, yes after renaming `my_prog` it now works.

A few other confusing points:
* If `import my_script` display any message to stdout (e.g. some libraries display deprecation warning), then it seem `eval "$(shtab --shell=bash my_script.get_main_parser)"` will try to execute those error messages
* It's not clear what `$BASH_COMPLETION_COMPAT_DIR` correspond too. It is empty on my system. Are we supposed to `export BASH_COMPLETION_COMPAT_DIR=` ourself ? If so which value should it be ?

**Comment by casperdcl** [comment]
>     * If `import my_script` display any message to stdout (e.g. some libraries display deprecation warning), then it seem `eval "$(shtab --shell=bash my_script.get_main_parser)"` will fail while trying to execute those messages.

Error messages should be logged to `stderr`, not `stdout`

>     * It's not clear what `$BASH_COMPLETION_COMPAT_DIR` correspond too.

Older versions of bash completion may set this env var to a directory where you can place completion scripts. See the commands in https://github.com/iterative/shtab#eager-bash for other places where you may install scripts system-wide.

**Comment by Conchylicultor** [comment]
Thank you you for the clarification. The issue could be close, unless you're plan to update the doc
