### ISSUE TITLE
zsh sub-subcommand recursion

### ISSUE THREAD

**Issue by skshetry** [iterative/shtab#33]
`shtab` does not seem to provide autocompletion for subcommands for `zsh`, whereas it does so for the `bash`. Only the parent's flags are shown (`-h`/`-q`/`-v` in the DVC's case).

https://github.com/iterative/shtab/blob/a519f261f11ccbbc67f789d8c169ebfc56cd89c0/shtab/__init__.py#L180

**Comment by skshetry** [comment]
@casperdcl, do you have any good resource/documentation on zsh autocompletion, especially something that's a bit complicated?

**Comment by casperdcl** [comment]
None that I know of; plus I don't use `zsh` otherwise I would've implemented this ages ago :)

Feel free to take a s(h)tab at it!
