### ISSUE TITLE
Inconsistencies with expected completions behavior

### ISSUE THREAD

**Issue by bmorledge-hampton19** [iterative/shtab#37]
Shtab has some interesting quirks in the completions it generates that deviate from what I am used to seeing, and I am having trouble figuring out if they are intentional or just bugs.

First, if there is only one possible option for completion of a command when I press tab, I expect completions to finish writing the command for me and then add a space, indicating that the command is complete and allowing me to immediately start writing the next command, or an argument to that command, etc.  Instead, the command gets completed, but no space is added, despite the fact that nothing helpful could be added to the command at that point (except a space).

Second, the file completion support through the shtab.FILE option has a similar issue.  When I am attempting to complete a file path using this option, if I try to navigate into a new directory and the text I have provided so far is sufficient to determine that directory, pressing tab does not autocomplete to take me into that directory.  Instead, two options are given:  One for the directory path without the forward slash, and one with the forward slash.  For example, if I type "/us" and hit tab, the path is expanded to "/usr" and two options are given: "/usr" and "/usr/".  All other completions I have used would see these as the same option and autocomplete to "/usr/" so that I can continue typing the file path until I reach the destination file.  Interestingly enough, using the shtab.DIRECTORY option produces the desired behavior, except that a file cannot be selected at the end of the file path.

Lastly, In addition to the above point, shtab.FILE and shtab.DIRECTORY don't handle completions for larger file paths as expected.  If a path across several directories is given, completions for any additional directories include every other directory up to that point instead of just the relevant directory.  As an example, if the text "/green/eggs/and/ham" is provided and tab is pressed twice, the options "/green/eggs/and/ham/" and "green/eggs/and/hamburgers/" are given instead of just "ham/" and "hamburgers/".  This method of displaying completion options can get VERY cluttered for large file paths.

These aspects of the shtab generated completions are very strange to me since they seem to go against every other set of completions that I have worked with in the Ubuntu bash terminal.  If these are intended features, what is the rationale behind them, and could it be possible to allow for completions in a more "native" form?

**Comment by casperdcl** [comment]
`shtab.FILE` really means "filesystem object" (i.e. potentially including dirs) rather than just "file."

1. `shtab.FILE` unexpectedly producing both `/usr` and `/usr/`: sounds like a feature request for something like `shtab.FILE_NOT_DIRECTORY` to produce just `/usr/` allowing for further completion
2. no space after completions: related to above point (1) where we don't know if a slash should be appended. Perhaps could change in certain scenarios.
3. completion displaying full paths rather than ends: not sure why this happens. feature request.

If you have any better suggestions, the relevant bash lines are https://github.com/iterative/shtab/blob/d93d6afcff5b2e2111814a237ac3571b78e12607/shtab/__init__.py#L268-L277

**Comment by bmorledge-hampton19** [comment]
Thank you for the speedy response.  

With respect to the first point you raised, I'm not sure that this merits another tag.  It doesn't seem uncommon to me to want to search for a path to a file by passing through a few directories on the way.  Is there no easy way to distinguish between directories and files and only append the slashes to the directories?  Could this also help with the second point?

My comments arise from noticing that these completions act very differently from most of the others I'm used to seeing.  Unfortunately, I'm not sure why that is.  I wish I had better suggestions for the bash lines used to generate the completions, but truth be told, I have almost no experience writing completions scripts myself.  Perhaps this is a good opportunity to educate myself a bit.

I may do some research and try to experiment with the completion script that shtab is generating.  If I come up with anything, I'll be sure to post it here.  This tool has already been immensely helpful to me, and I'd love to be able to give back to the development process if I'm able.

**Comment by casperdcl** [comment]
one suggestion may be:

```diff
-  compgen -f -- $1  # files 
+  comm -23 <(compgen -f -- $1 | sort) <(compgen -d -- $1 | sort)
```

That would mean `/usr`, `/usr/` becomes just `/usr/`

**Comment by bmorledge-hampton19** [comment]
I may have found a solution that addresses all of the relevant feature requests:

```diff
_shtab_compgen_files() { 
   compgen -f -- $1  # files
-  compgen -d -S '/' -- $1  # recurse into subdirs
}

-  complete -o nospace -F {root_prefix} {prog}""",
+  complete -o filenames -F {root_prefix} {prog}""",
```

Admittedly, I'm somewhat worried about potential side effects from changing the comp-option of the entire completions script, but for the few test cases that I put it through, there didn't seem to be any deviations from expected behaviors.  Thoughts?

**Comment by casperdcl** [comment]
I've done some tests and it seems to work quite well. It's far more elegant than the source code for completing e.g. `cp` (https://github.com/scop/bash-completion/blob/d1c13dafe7494cb0727d4874f22491c661ea3662/bash_completion#L2099-L2149)

**Comment by bmorledge-hampton19** [comment]
Great!  I'm so glad it helped!  I'm learning a lot about bash scripting and completions throughout this whole process too, which is a plus.  I'm going to try my hand at finding a solution to issue #11 as well, since I would like to have that functionality as well.

**Comment by bmorledge-hampton19** [comment]
Success!!! (I think)  I've made some largescale modifications to [shtab/\_\_init\_\_.py](https://github.com/iterative/shtab/blob/master/shtab/__init__.py) which I think go a long ways in making the completions generation more robust.  More details are in pull request #38.  (This is the first time I've contributed to a project like this, so if I'm doing something wrong with the pull request, please let me know.)  

I've tested these changes on a few basic cases and as far as I can tell, they hold up pretty well.  I welcome more rigorous testing though, as I know I still have a lot to learn about argparse, bash completion scripting, and shtab.  Please let me know if there are any changes that need to be made or further issues I can help with.  I will be away from my computer this weekend but will be back by Tuesday, so my apologies in advance if I don't reply until later.
