### ISSUE TITLE
1.3.7 is missing tar.gz on pypi

### ISSUE THREAD

**Issue by efiop** [iterative/shtab#40]
E.g. 1.3.6 has it https://pypi.org/project/shtab/1.3.6/#files, but 1.3.7 doesn't https://pypi.org/project/shtab/1.3.7/#files , which broke our homebrew formula update, as it needs that resource.

**Comment by chenrui333** [comment]
FYI, I have raised a [dvc 2.5.0 PR](https://github.com/Homebrew/homebrew-core/pull/80603) using the old 1.3.6 release.

**Comment by casperdcl** [comment]
Are you sure you can't use the `*.whl` instead? I can reenable if required.

**Comment by efiop** [comment]
Discussed this in private messages, but just for the record: brew and conda https://github.com/conda-forge/shtab-feedstock/blob/master/recipe/meta.yaml#L9 rely on tar.gz on pypi. Probably more tools rely on that. So yeah, we need to brings back the tars.

**Comment by casperdcl** [comment]
k `shtab==1.3.8` released now

**Comment by chenrui333** [comment]
Thanks @casperdcl!
