### ISSUE TITLE
Control fallback

### ISSUE THREAD

**Issue by psacawa** [iterative/shtab#45]
In cases where argparse is expecting a flag, pressing *tab* doesn't generate any output. In these cases, it would be useful to implement a fallback completion. This could be the list of flags themselves, or a programmable completion set during the shtab invocation. For example, zsh implements the `_default` completion utility, installed at `/usr/share/zsh/functions/Completion/Zsh/_default`.

This is more ergonomic than the current behaviour of no output, and is consistent with the majority of third-party completion scripts I've seen in the wild.

**Comment by casperdcl** [comment]
I don't understand. Can you give an example?

```bash
shtab (master)$ eval "$(PYTHONPATH=$PWD python examples/pathcomplete.py -s bash)"
shtab (master)$ pathcomplete -  # TAB
--dir               -h                  --help              --print-completion  -s
```

**Comment by psacawa** [comment]
Reading my comment, I can see I didn't communicate correctly. What I talking about the state of the command line with the comand name and nothing else:
```
pathcomplete <TAB>
```

For my zsh conf, most commands fallback to listing files via `_files`, which is often a sensible fallback. I *may* be valuable to provide this as an option  for command line invocations of Z`shtab`

**Comment by casperdcl** [comment]
AFAIK on `bash` this is default behaviour. See e.g.

```bash
cp <TAB>
grep <TAB>
```

**Comment by psacawa** [comment]
Over here I have the file fallback for `cp`, but not for `grep` (expecting pattern). This is on Ubuntu 20.04 with  `_cp` supplied by `zsh-common` APT package, which invokes `_files`.

**Comment by casperdcl** [comment]
Exactly - `cp` does expect a file positional arg and thus suggests it. `grep` does not. However neither will suggest option flags unless you type `-<TAB>`. This is exactly how `shtab` behaves.

**Comment by casperdcl** [comment]
closing as it seems `shtab` is behaving as expected identical to common UNIX commands. Happy to re-open if there's some discrepancy.
