### ISSUE TITLE
Type hints?

### ISSUE THREAD

**Issue by woodruffw** [iterative/shtab#59]
Hi there!

First of all, thanks for making this library -- it's _exactly_ what I was looking for in terms of tab completion generation 🙂

I'm currently evaluating `shtab` for use in [pip-audit](https://github.com/trailofbits/pip-audit). Our codebase is 100% typechecked with MyPy, so we're also reaching out to our upstream dependencies and seeing whether they do/would like to support type hints as well.

From a quick glance it looks like `shtab/__init__.py` doesn't have any type hints yet, but it also looks relatively short and like it wouldn't be too much of a lift. From there, the only other step needed for exposing types to your downstream users is to add a PEP561-style `py.typed` file to your source directory and ensure that it's included in your packaged distributions.

Is there any interest in doing that?

**Comment by casperdcl** [comment]
sure, happy to accept contributions.

**Comment by woodruffw** [comment]
Awesome. I'll take a stab at it today.
