### ISSUE TITLE
Simple way to configure enum style completions

### ISSUE THREAD

**Issue by mauvilsa** [iterative/shtab#68]
There is some interest in making [jsonargparse](https://github.com/omni-us/jsonargparse) more usable with shtab. Ideally, when people use jsonargparse many shtab features would work out-of-the-box, avoiding the need for them to implement boilerplate. No need to set `completer` for each added argument. When jsonargparse is used with argcomplete, it works like this already and it would be great if it worked the same for shtab. I am no expert on shtab, but it seems that the same features are not as simple to do with shtab.

The first use case that would be good to support is arguments that expect one among several fixed strings. An example parser is:

```python
from enum import Enum
from jsonargparse import ArgumentParser
from typing import Optional

class MyEnum(Enum):
    abc = 1
    xyz = 2

parser = ArgumentParser()
parser.add_argument('--bool', type=Optional[bool])
parser.add_argument('--enum', type=Optional[MyEnum])
parser.add_argument('--enums', type=MyEnum, nargs='+')
parser.parse_args()
```

The behavior in the command line that would be expected is:

```bash
$ cli.py --bool <TAB><TAB>
false  true  null
$ cli.py --bool f<TAB>
$ cli.py --bool false

$ cli.py --enum <TAB><TAB>
abc  xyz  null
$ cli.py --enum n<TAB>
$ cli.py --enum null

$ cli.py --enums abc <TAB><TAB>
abc  xyz
$ cli.py --enums abc x<TAB>
$ cli.py --enums abc xyz
```

Another use case is a mixture of fixed strings and a path. An example parser is:

```python
from jsonargparse import ArgumentParser
from jsonargparse.typing import Path_fr
from typing import Optional

parser = ArgumentParser()
parser.add_argument('--file', type=Optional[Path_fr])
parser.parse_args()
```

And the behavior in the command line:

```bash
$ ./example.py --file <TAB><TAB>
file1.txt  file2.txt  null
$ ./example.py --file f<TAB>
$ ./example.py --file file<TAB>
file1.txt  file2.txt
$ ./example.py --file file2<TAB>
$ ./example.py --file file2.txt
```

An optional path is just one example. The point is that the type could be a combitation of things, e.g `type=Union[Path_fr, MyEnum]`.

To avoid boilerplate, the idea would be that jsonargparse on the `add_argument` call, internally adds the required information to the action object, such that shtab knows how to process it. Furthermore, with jsonargparse big parsers can be automatically created from signatures of functions and classes. With such parsers it is not practical for people to implement what shtab should do for each option.

Is there already a simple way to implement these use cases with shtab? If so, how to do it? Note that these completions are completely independent from what shell is used. Thus, I would expect a way which is simple and not shell-dependent. For example, something like:

```python
# for type=Optional[bool]
action.complete = shtab.enum_completer(["false", "true", "null"])
# for type=Optional[MyEnum]
action.complete = shtab.enum_completer(["abc", "xyz", "null"])
# for type=Optional[Path_fr]
action.complete = [shtab.FILE, shtab.enum_completer(["null"])]
```

**Comment by casperdcl** [comment]
See https://github.com/iterative/shtab/pull/136#issuecomment-1593788135 for a potential work-around?
