### ISSUE TITLE
setup.cfg on PyPI is not bit-identical with setup.cfg in git

### ISSUE THREAD

**Issue by fmoessbauer** [iterative/shtab#80]
Hi,

I'm working on packaging shtab for Debian and while doing so I discovered a reproducability glitch:
The `setup.cfg` in the git repository uses `key=value`, while the `setup.cfg` in the archive from PyPI uses `key = value` syntax (note the spaces).

This is problematic as we assume that the sources archive distributed via PyPI is identical with the upstream repository.

**Comment by casperdcl** [comment]
I'm not sure you're meant to compare `setup.cfg` byte-for-byte.

If you need to programmatically check consistency, you could parse the files (into dicts/objects) first. afaik the PyPI file is generated by `python setup.py sdist` and therefore has different whitespaces plus also an extra block:

```
[egg_info]
tag_build =
tag_date = 0
```

**Comment by fmoessbauer** [comment]
Ok, thanks for the clarification. Then I'll simply use the archive from PyPI.
