### ISSUE TITLE
bash: Multiple subparser commands don't complete correctly

### ISSUE THREAD

**Issue by NiklasReisser** [iterative/shtab#86]
Hi,

since #81 , shtab always only completes the first subparser command. The minimal example below immediately completes "bla". 

The Reason seems to be that https://github.com/iterative/shtab/blob/60a8525707f10859513c4362ea9c62cd40db93b8/shtab/__init__.py#L357
only expands the first value of the _choices array. Unfortunately, I have not found a solution without breaking #81 again. 
Happy to try any idea though. 
  
```

#!/usr/bin/env python3

import argparse
import shtab

parser = argparse.ArgumentParser()
shtab.add_argument_to(parser, ["--print-completion"])

subparsers = parser.add_subparsers()

subparser1 = subparsers.add_parser('bla', help="hi")
subparser2 = subparsers.add_parser('blub', help="hi")

args = parser.parse_args()

```

Cheers
Niklas

**Comment by pared** [comment]
DVC has issues with that too:
https://discord.com/channels/485586884165107732/485596304961962003/1034753563966050395

**Comment by alkatar21** [comment]
I have the Issue with DVC tab completion.

Current workaround as suggested in Discord is:
1. Downgrade shtab (`pip install shtab==1.5.4`)
2. `dvc completion -s bash | sudo tee /etc/bash_completion.d/dvc`
3. reload terminal/ open a new one, try again

**Comment by casperdcl** [comment]
Related: #106

**Comment by shcheklein** [comment]
@casperdcl thanks! :)

**Comment by shcheklein** [comment]
@alkatar21 could you give the new version a try?

**Comment by alkatar21** [comment]
Yes, the subcommands autocomplete correct again, thanks👍
