### ISSUE TITLE
[feature] why shtab don't have shell completion by itself?

### ISSUE THREAD

**Issue by Freed-Wu** [iterative/shtab#89]
I notice shtab.main.get_main_parser don't use `shtab.add_argument_to`. Can it do?

**Comment by casperdcl** [comment]
Doggfooding à la https://docs.iterative.ai/shtab/use/#library-usage? Sure...

**Comment by Freed-Wu** [comment]
I know we can use `shtab --shell=tcsh shtab.main.get_main_parser --error-unimportable | sudo tee /etc/profile.d/shtab.completion.csh` to generate shell completion. I want to know
why not `shtab --print-completion XXX`? The latter looks better.

**Comment by casperdcl** [comment]
Yes makes sense, feel free to add it :)
